//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYAME_s_World.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8wuIDkzkK0ICVs3YrvG5UqlQC")]
        public string API_KEY {
            get {
                return ((string)(this["API_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8tyqLi7X3r5zlU3BGRvB5jXU7vvIktmSNd3Rr8SjiAgY9DGYyq")]
        public string API_KEY_SECRET {
            get {
                return ((string)(this["API_KEY_SECRET"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20587752-739HVZEqPxeDjiX4qcRQGDYFBg1WBdq12BdH74sBv")]
        public string TOKEN_KEY {
            get {
                return ((string)(this["TOKEN_KEY"]));
            }
            set {
                this["TOKEN_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bN29DRdxjODUzc9XARwEp6OWcRMgMfaZIQ0nSXZyCvBKA")]
        public string TOKEN_SECRET {
            get {
                return ((string)(this["TOKEN_SECRET"]));
            }
            set {
                this["TOKEN_SECRET"] = value;
            }
        }
    }
}
